abilities=struct('ip',struct('c',1,'Sm',0.08,'Sx',0.12,'Sh',3185,'Am',0,...
                             'w',0,'mult',1.05,'cb',0.0,'sb',0.0,'s30',0.1,'ctype',1,'ct',0,...
                             'base_acc',1,'raid_mult',1.0,'name','Ion Pulse','dmg_type',3,...
                             'id','ionpulse','CD',0,'raidAOE',0,'raidIE',1,'raidKEFT',1),...
                 'hs',struct('c',1,'Sm',0,'Sx',0,'Sh',3185,'Am',0,'CD',0,...
                             'w',1,'mult',1,'cb',0.0,'sb',0.,'s30',0.15,'ctype',1,'ct',0,...
                             'base_acc',1,'raid_mult',1.05,'name','Hammer Shot','dmg_type',1,...
                             'id','hammershot','ticks',7,...
                             'raidAOE',0,'raidIE',0,'raidKEFT',1),...
                 'iri',struct('c',0.41,'Sm',0.021,'Sx',0.061,'Sh',3185,'Am',0,...
                              'w',0,'mult',1.0,'cb',0.0,'sb',0.,'s30',0.1,'ctype',1,'ct',0,...
                              'id','incendiaryroundinitial','CD',9, ...
                              'base_acc',1,'raid_mult',1.0,'name','Incendiary Round','dmg_type',3,...
                              'callback','IRCallback',...
                             'raidAOE',0,'raidIE',1,'raidKEFT',1),...
                 'ird',struct('c',0.34,'Sm',0.034,'Sx',0.034,'Sh',3185,'Am',0,...
                              'w',0,'mult',1.0,'cb',0.,'sb',0.,'s30',0.1,'ctype',4,'ct',0,...
                              'int',3,'dur',15,'id','incendiaryrunddot','CD',0,'initial_tick',0, ...
                              'base_acc',1,'raid_mult',1.123,'name','Incendiary Round DOT','dmg_type',3,...
                             'raidAOE',0,'raidIE',1,'raidKEFT',1),...
                 'pt' ,struct('c',0.370,'Sm',0.037,'Sx',0.037,'am',0.000,'Sh',3185,...
                              'w',0,'long_id','abl.trooper.skill.plasmatech.plasmatize','id','plasmatize','name','Plasmatize',...
                              'cb',0.0,'sb',0.3,'s30',0.1,'dmg_type',3,'base_acc',1.0,'raid_mult',1.0,...
                              'ctype',4,'ct',0.0,'mult',1.0,'CD',0.000000,'dur',30,'int',3,...
                             'raidAOE',0,'raidIE',1,'raidKEFT',1),...
                 'sc',struct('c',0.98,'Sm',0.078,'Sx',0.118,'Sh',3185,'Am',0,...
                              'w',0,'mult',1.,'cb',0.0,'sb',0.,'s30',0,'ctype',-1,'ct',0,...
                              'base_acc',1,'raid_mult',1.00,'name','Shoulder Cannon','dmg_type',2,...
                              'id','shouldercannon','CD',0,...
                             'raidAOE',0,'raidIE',0,'raidKEFT',1),...
                 'hib' ,struct('c',1.97,'Sm',0.197,'Sx',0.197,'Sh',3185,'Am',0.31,...
                              'w',1,'mult',1.00,'cb',0.0,'sb',0.0,'s30',0,'ctype',1,'ct',0,...
                              'base_acc',1,'raid_mult',1.00,'name','High Implact Bolt','dmg_type',1,...
                              'id','hib','CD',0,'armor_pen',0.6,...
                             'raidAOE',0,'raidIE',0,'raidKEFT',1),...
                 'fp' ,struct('c',1.74,'Sm',0.154,'Sx',0.194,'Sh',3185,'Am',0,...
                               'w',0,'mult',1.0,'cb',0.0,'sb',0.3,'s30',0.1,'ctype',1,'ct',2,...
                               'base_acc',1,'raid_mult',1.0,'name','Fire Pulse','dmg_type',3,...
                               'id','firepulse','CD',15,...
                             'raidAOE',0,'raidIE',1,'raidKEFT',1),...
                 'pc',struct('c',0.555,'Sm',0.0555,'Sx',0.0555,'Sh',3185,'Am',0,...
                              'w',0,'mult',1.0,'cb',0.,'sb',0.3,'s30',0.1,'ctype',3,'ct',3,...
                              'id','pulsecannon','CD',0,'initial_tick',0, ...
                              'base_acc',1,'raid_mult',1.0,'name','Pulse Cannon','dmg_type',3,'ticks',4,...
                             'raidAOE',1,'raidIE',1,'raidKEFT',1),...
                 'ssk',struct('c',1.78,'Sm',0.158,'Sx',0.198,'Sh',3185,'Am',0,...
                              'w',0,'mult',1.1,'cb',0.0,'sb',0.3,'s30',0,'ctype',1,'ct',0,...
                               'id','shockstrike','CD',0,'initial_tick',0, ...
                              'base_acc',1,'raid_mult',1.00,'name','Shockstrike','dmg_type',1,...
                              'callback','ShockCallback',...
                             'raidAOE',0,'raidIE',0,'raidKEFT',1),...
                 'ssi',struct('c',0.41,'Sm',0.021,'Sx',0.061,'Sh',3185,'Am',0,...
                              'w',0,'mult',1.1,'cb',0.0,'sb',0.3,'s30',0.1,'ctype',0,'ct',0,...
                               'id','shockstrikeinternal','CD',0,'initial_tick',0, ...
                              'base_acc',1,'raid_mult',1.00,'name','Shockstrike ele','dmg_type',3,...
                             'raidAOE',0,'raidIE',1,'raidKEFT',1),...
                 'pcd',struct('c',0.1715,'Sm',0.017,'Sx',0.017,'Sh',3185,'Am',0,...
                              'w',0,'mult',1.3,'cb',0.0,'sb',0.,'s30',0.1,'ctype',4,'ct',0,...
                               'id','plasmacelldot','CD',0,'initial_tick',1,'int',3,'dur',6, ...
                              'base_acc',1,'raid_mult',1.0,'name','Plasma Cell','dmg_type',3,...
                             'raidAOE',0,'raidIE',1,'raidKEFT',1));
                          
                          
dots=struct('PCD',struct('LastUsed',-1,'NextTick',-1,...
                         'Expire',-1,'WExpire',-1,...
                         'Ala',1.0,'it','pcd'),...
             'IR',struct('LastUsed',-1,'NextTick',-1,...
                         'Expire',-1,'WExpire',-1,...
                         'Ala',1.0,'it','ird'),...
             'PT',struct('LastUsed',-1,'NextTick',-1,...
                         'Expire',-1,'WExpire',-1,...
                         'Ala',1.0,'it','pt'));
buffs=struct('BF',struct('LastUsed',-1,'Available',0,'Dur',15,'CD',120),...
             'AD',struct('LastUsed',-1,'Available',0,'Dur',15),...
             'BARelic',struct('LastUsed',-1,'Available',0,'Dur',30));
procs=struct('FR',struct('LastProc',-1,'Dur',6,'CD',20),...
             'SA',struct('LastProc',-1,'Dur',6,'CD',20),...
             'PC2',struct('LastProc',-1,'Dur',15,'CD',30,'Available',0),...
             'HAC',struct('LastProc',-1,'Dur',15,'CD',0,'Charges',0),...
             'PG',struct('LastProc',-1,'Dur',15,'CD',0,'Charges',0),...
             'PCD',struct('LastProc',-1,'Dur',6,'CD',0,'Available',0));
                           
z=struct('abilities',abilities,'dots',dots,'buffs',buffs,'procs',procs);
json.savejson('',z,'json/Plasmatech.json');