abilities=struct('ds',struct('c',0.775,'Sm',0.0775,'Sx',0.0775,'Sh',3185,'Am',-0.48,...
                             'w',1,'mult',1.05,'cb',0.0,'sb',0.3,'s30',0,'ctype',1,'ct',0,...
                             'base_acc',1,'raid_mult',1.00,'name','Double Strike','dmg_type',2,...
                             'id','doublestrike','CD',0,'hits',2,...
         'raidAOE',0,'raidIE',0,'raidKEFT',1),...
                 'fib',struct('c',1.81,'Sm',0.161,'Sx',0.201,'Sh',3185,'Am',0,'CD',9,...
                             'w',0,'mult',1,'cb',0.0,'sb',0.,'s30',0.15,'ctype',1,'ct',0,...
                             'base_acc',1,'raid_mult',1.0,'name','Force in Balance','dmg_type',3,...
                             'id','fib','callback','FIBCallback',...
         'raidAOE',1,'raidIE',1,'raidKEFT',1),...
                 'sf',struct('c',0.36,'Sm',0.036,'Sx',0.036,'Sh',3185,'Am',0,...
                              'w',0,'mult',1.2,'cb',0.0,'sb',0.,'s30',0.15,'ctype',4,'ct',0,...
                              'int',3,'dur',18,'id','severforce','CD',9, ...
                              'base_acc',1,'raid_mult',1.0,'name','Sever Force','dmg_type',3,...
         'raidAOE',0,'raidIE',1,'raidKEFT',1),...
                 'fb',struct('c',0.39,'Sm',0.039,'Sx',0.039,'Sh',3185,'Am',0,...
                              'w',0,'mult',1.3,'cb',0.,'sb',0.,'s30',0.15,'ctype',4,'ct',0,...
                              'int',3,'dur',18,'id','forcebreach','CD',0, ...
                              'base_acc',1,'raid_mult',1.00,'name','Force Breach','dmg_type',1,...
         'raidAOE',0,'raidIE',0,'raidKEFT',1),...
                 'sps' ,struct('c',2.657,'Sm',0.266,'Sx',0.266,'Sh',3185,'Am',0.77,...
                              'w',1,'mult',1.0,'cb',0.0,'sb',0.3,'s30',0.,'ctype',1,'ct',0,...
                              'base_acc',1,'raid_mult',1.00,'name','Spinning Strike','dmg_type',2,...
                              'id','spinstrike','CD',0,...
         'raidAOE',0,'raidIE',0,'raidKEFT',1),...
                 'sas',struct('c',0.33,'Sm',0.,'Sx',0.,'Sh',3185,'Am',-0.66,...
                              'w',1,'mult',1.,'cb',0.0,'sb',0.,'s30',0,'ctype',1,'ct',0,...
                              'base_acc',0.9,'raid_mult',1.00,'name','Saber Strike','dmg_type',2,...
                              'id','saberstrike','CD',0,'hits',3,...
         'raidAOE',0,'raidIE',0,'raidKEFT',1),...
                 'ses' ,struct('c',1.86,'Sm',0.186,'Sx',0.186,'Sh',3185,'Am',0.24,...
                              'w',1,'mult',1.05,'cb',0.0,'sb',0.3,'s30',0,'ctype',1,'ct',0,...
                              'base_acc',1,'raid_mult',1.05,'name','Serenity Strike','dmg_type',1,...
                              'id','serenitystrike','CD',12,'callback','SESCallback',...
         'raidAOE',0,'raidIE',0,'raidKEFT',1),...
                 'vq' ,struct('c',1.295,'Sm',0.1109,'Sx',0.149,'Sh',3185,'Am',0,...
                               'w',0,'mult',1.2,'cb',0.0,'sb',0.,'s30',0.15,'ctype',2,'ct',2,...
                               'base_acc',1,'raid_mult',1.00,'name','Vanquish','dmg_type',2,...
                               'id','vanquish','CD',0,'callback','VQCallback',...
         'raidAOE',0,'raidIE',1,'raidKEFT',1),...
                 'vqd',struct('c',0.35,'Sm',0.035,'Sx',0.035,'Sh',3185,'Am',0,...
                              'w',0,'mult',1.3,'cb',0.,'sb',0.,'s30',0.15,'ctype',4,'ct',0,...
                              'int',1,'dur',6,'id','vanquishdot','CD',0,'initial_tick',0, ...
                              'base_acc',1,'raid_mult',1.00,'name','Vanquish DOT','dmg_type',2,...
         'raidAOE',0,'raidIE',0,'raidKEFT',1),...
                 'ft',struct('c',0.234,'Sm',0.0234,'Sx',0.0234,'Sh',3185,'Am',0,...
                              'w',0,'mult',1,'cb',0.5,'sb',0.,'s30',0,'ctype',0,'ct',0,...
                               'id','forcetech','CD',0,'initial_tick',0, ...
                              'base_acc',1,'raid_mult',1.0,'name','Force Technique','dmg_type',1,...
         'raidAOE',0,'raidIE',0,'raidKEFT',1));

dots=struct('SF',struct('LastUsed',-1,'NextTick',-1,...
                         'Expire',-1,'WExpire',-1,...
                         'Ala',1.0,'it','sf'),...
            'VQ',struct('LastUsed',-1,'NextTick',-1,...
                         'Expire',-1,'WExpire',-1,...
                         'Ala',1.0,'it','vqd'),...
            'FB',struct('LastUsed',-1,'NextTick',-1,...
                         'Expire',-1,'WExpire',-1,...
                         'Ala',1.0,'it','fb'));
buffs=struct('BR',struct('LastUsed',-1,'Available',0,'Dur',15,'CD',120),...
             'AD',struct('LastUsed',-1,'Available',0,'Dur',15),...
             'BARelic',struct('LastUsed',-1,'Available',0,'Dur',30),...
             'FP',struct('LastUsed',-1,'Available',0,'Dur',20,'CD',90,'Charges',0),...
             'FiB',struct('LastUsed',-1,'Available',-1,'Dur',30,'Charges',0));
procs=struct('FR',struct('LastProc',-1,'Dur',6,'CD',20),...
             'SA',struct('LastProc',-1,'Dur',6,'CD',20),...
             'PC2',struct('LastProc',-1,'Dur',15,'CD',30,'Available',0),...   %Stakler set bonus
             'FS',struct('LastProc',-1,'Dur',30,'CD',0),...   %Force Synergy
             'CS',struct('LastProc',-1,'Dur',10,'CD',6,'Available',0.0),... %Crush Spirit
             'FoS',struct('LastProc',-1,'Dur',15,'CD',9,'Available',0),...
             'FT',struct('LastProc',-1,'Dur',15,'CD',1.5,'Available',0));
                           
z=struct();
z.abilities=abilities;
z.dots=dots;
z.buffs=buffs;
z.procs=procs;
json.savejson('',z,'json/Serenity.json');