abilities=struct('sn',struct('c',1.74,'Sm',0.174,'Sx',0.174,'Sh',3185,'Am',0.16,...
                             'w',1,'mult',1.05,'cb',0.04,'sb',0.3,'s30',0,'ctype',2,'ct',1.5,...
                             'base_acc',1,'raid_mult',1.00,'name','Snipe','dmg_type',1,...
                             'callback','SNCallback','id','snipe','CD',0,...
    'raidAOE',0,'raidIE',0,'raidKEFT',1),...
                 'pb',struct('c',0.847,'Sm',0.085,'Sx',0.085,'Sh',3185,'Am',-0.44,...
                             'w',1,'mult',1.05,'cb',0.15,'sb',0.3,'s30',0,'ctype',3,'ct',2,...
                             'base_acc',1,'raid_mult',1.00,'name','Penetrating Blasts','dmg_type',1,...
                             'ticks',5,'id','penblast','CD',12,...
    'raidAOE',0,'raidIE',0,'raidKEFT',1),...
                 'td',struct('c',2.51,'Sm',0.251,'Sx',0.251,'Sh',3185,'Am',0.67,...
                              'w',1,'mult',1.0,'cb',0.15,'sb',0.3,'s30',0,'ctype',1,'ct',0,...
                              'base_acc',1,'raid_mult',1.00,'name','Takdedown','dmg_type',1 ...
                              ,'id','takedown','CD',12,...
    'raidAOE',0,'raidIE',0,'raidKEFT',1),...
                 'ft',struct('c',1.97,'Sm',0.192,'Sx',0.192,'Sh',3185,'Am',0.28,...
                              'w',1,'mult',1.0,'cb',0.04,'sb',0.3,'s30',0,'ctype',1,'ct',0,.....
                              'base_acc',1,'raid_mult',1.00,'name','Followthrough','dmg_type',1 ...
                              ,'id','ft','CD',0,...
    'raidAOE',0,'raidIE',0,'raidKEFT',1),...
                 'amb',struct('c',3.684,'Sm',0.37,'Sx',0.37,'Sh',3185,'Am',1.36,...
                              'w',1,'mult',1.00,'cb',0.02,'sb',0.3,'s30',0,'ctype',2,'ct',2,.....
                              'base_acc',1,'raid_mult',1.00,'name','Ambush','dmg_type',1 ...
                              ,'armor_pen',0.2,'callback','AMBCallback','id','ambush','CD',12,...
    'raidAOE',0,'raidIE',0,'raidKEFT',1),...
                 'cd',struct('c', 0.3075 ,'Sm',0.03075,'Sx',0.03075,'Sh',3185,'Am',0,...
                             'w',0,'mult',1.0,'cb',0.0,'sb',0,'s30',0.0,'ctype',4,'ct',0,...
                             'int',3,'dur',18,'dmg_type',3,'id','dart','CD',0,...
                             'base_acc',1,'raid_mult',1.0,'name','Corrosive Dart',...
    'raidAOE',0,'raidIE',1,'raidKEFT',1),...
                 'rs',struct('c', 0.5 ,'Sm',0.0,'Sx',0.0,'Sh',3185,'Am',-0.50,...
                             'w',1,'mult',1.0,'cb',0.1,'sb',0,'s30',0.0,'ctype',1,'ct',0,...
                             'base_acc',0.9,'raid_mult',1.00,'name','Rifle Shot','dmg_type',1,...
                             'id','rifleshot','CD',0,...
    'raidAOE',0,'raidIE',1,'raidKEFT',1),...    
    'xs',struct('c',0.7,'Sm',0.070,'Sx',0.070,'Am',0.000,'Sh',3185,...
         'w',0,'long_id','abl.exp.02.yavin_4.world_arc.the_enemy_within.theron_shan.xs_freighter_flyby','id','xs_freighter_flyby','name','XS Freighter Flyby',...
         'cb',0.0,'sb',0.0,'s30',0.0,'dmg_type',3,'base_acc',1.0,'raid_mult',1.0,...
         'ctype',4,'ct',2.0,'mult',1.0,'CD',45.000000,'int',3,'dur',9,'initial_tick',0,'entersCombat',0,...
         'raidAOE',1,'raidIE',1,'raidKEFT',1)...
                         );
dots=struct('CD',struct('LastUsed',-1,'NextTick',-1,...
                         'Expire',-1,'WExpire',-1,...
                         'Ala',1.0,'it','cd'),...
            'XS',struct('LastUsed',-1,'NextTick',-1,...
                         'Expire',-1,'WExpire',-1,...
                         'Ala',1.0,'it','xs'));
buffs=struct('TA',struct('LastUsed',-1,'Available',0,'Dur',10),...
             'LT',struct('LastUsed',-1,'Available',0,'Dur',20),...
             'AD',struct('LastUsed',-1,'Available',0,'Dur',15),...
             'BARelic',struct('LastUsed',-1,'Available',0,'Dur',30),...
             'SV',struct('LastUsed',-1,'Available',0,'Dur',15));
procs=struct('FR',struct('LastProc',-1,'Dur',6,'CD',20),...
             'SA',struct('LastProc',-1,'Dur',6,'CD',20),...
             'HS',struct('LastProc',-1,'Dur',20,'CD',0,'Charges',0),...
             'ZS',struct('LastProc',-1,'Dur',10,'CD',0,'Charges',0),...
             'PC2',struct('LastProc',-1,'Dur',15,'CD',30,'Available',0));
                           
z=struct('abilities',abilities,'dots',dots,'buffs',buffs,'procs',procs);
json.savejson('',z,'json/Marksman.json');
abilities.cd.name='Vital Shot';
abilities.sn.name='Charged Burst';
abilities.pb.name='Penetrating Rounds';
abilities.td.name='Quickdraw';
abilities.ft.name='Trickshot';
abilities.amb.name='Aimed Shot';
abilities.rs.name='Flurry of Bolts';
z=struct('abilities',abilities,'dots',dots,'buffs',buffs,'procs',procs);
json.savejson('',z,'json/Sharpshooter.json');