abilities=struct('ts',struct('c',1.72,'Sm',0.152,'Sx',0.192,'Sh',3185,'Am',0,...
                             'w',0,'mult',1.1025,'cb',0.0,'sb',0.3,'s30',0,'ctype',1,'ct',0,...
                             'base_acc',1,'raid_mult',1.00,'name','Tactical Surge','dmg_type',1,...
                             'callback','ProcCallback','id','tacsurge','CD',0,...
                             'raidAOE',0,'raidIE',0,'raidKEFT',1),...
                 'ss',struct('c',1.77,'Sm',0.158,'Sx',0.198,'Sh',3185,'Am',0,'CD',9,...
                             'w',0,'mult',1.249,'cb',0.05,'sb',0.3,'s30',0,'ctype',1,'ct',0,...
                             'base_acc',1,'raid_mult',1.00,'name','Stock Strike','dmg_type',1,...
                             'callback','ProcCallback','id','stockstrike',...
                             'raidAOE',0,'raidIE',0,'raidKEFT',1),...
                 'gut',struct('c',0.95,'Sm',0.075,'Sx',0.115,'Sh',3185,'Am',0,'CD',0, ...
                              'w',0,'mult',1.1025,'cb',0,'sb',0.3,'s30',0,'ctype',1,'ct',0,...
                              'base_acc',1,'raid_mult',1,'name','Gut','dmg_type',1,'id','gut',...
                              'callback','GUTCallback',...
                             'raidAOE',0,'raidIE',0,'raidKEFT',1),...
                 'gutd',struct('c',0.25,'Sm',0.025,'Sx',0.025,'Sh',3185,'Am',0,...
                              'w',0,'mult',1.2,'cb',0.0,'sb',0.3,'s30',0,'ctype',4,'ct',0,...
                              'int',3,'dur',24,'id','gutdot','CD',0, ...
                              'base_acc',1,'raid_mult',1.,'name','Gut DOT','dmg_type',3,...
                             'raidAOE',0,'raidIE',1,'raidKEFT',1),...
                 'cb' ,struct('c',0.840,'Sm',0.079,'Sx',0.089,'Sh',3185,'Am',0,...
                              'w',0,'mult',1.105,'cb',0.0,'sb',0.3,'s30',0,'ctype',1,'ct',0,...
                              'base_acc',1,'raid_mult',1.00,'name','Cell Burst','dmg_type',1,'charges',0,...
                              'callback','CBCallback','id','cellburst','CD',0,...
                             'raidAOE',0,'raidIE',0,'raidKEFT',1),...
                 'hib',struct('c',1.97,'Sm',0.197,'Sx',0.197,'Sh',3185,'Am',0.31,...
                              'w',1,'mult',1.105,'cb',0.0,'sb',0.3,'s30',0,'ctype',1,'ct',0,...
                              'base_acc',1,'raid_mult',1.00,'name','High Impact Bolt','dmg_type',1,...
                              'callback','HIBCallback','armor_pen',1.0,'id','hib','CD',15,...
                             'raidAOE',0,'raidIE',0,'raidKEFT',1),...
                 'hs' ,struct('c',1,'Sm',0.,'Sx',0.,'Sh',3185,'Am',0,...
                              'w',1,'mult',1.105,'cb',0.0,'sb',0,'s30',0,'ctype',1,'ct',0,...
                              'base_acc',0.9,'raid_mult',1.00,'name','Hammer Shot','dmg_type',1,...
                              'id','hammershot','CD',0,'ticks',7,...
                             'raidAOE',0,'raidIE',0,'raidKEFT',1),...
                 'ap' ,struct('c',2.48,'Sm',0.228,'Sx',0.268,'Sh',3185,'Am',0,...
                               'w',0,'mult',1.105,'cb',0.05,'sb',0.3,'s30',0,'ctype',4,'ct',0,...
                               'base_acc',1,'raid_mult',1.00,'name','Assault Plastique','dmg_type',1,...
                               'id','assaultplastique','CD',15,'int',3','dur',3,'initial_tick',0,...
                               'enters_combat',1,'raidAOE',0,'raidIE',0,'raidKEFT',1),...
                 'sc' ,struct('c',0.98,'Sm',0.078,'Sx',0.118,'Sh',3185,'Am',0,...
                               'w',0,'mult',1.305,'cb',0.02,'sb',0.0,'s30',0,'ctype',-1,'ct',0,...
                               'base_acc',1,'raid_mult',1.05,'name','Shoulder Cannon','dmg_type',1,...
                               'id','shouldercannon','CD',0,'raidAOE',0,'raidIE',0,'raidKEFT',1));
dots=struct('GUT',struct('LastUsed',-1,'NextTick',-1,...
                         'Expire',-1,'WExpire',-1,...
                         'Ala',1.0,'it','gutd'),...
             'AP',struct('LastUsed',-1,'NextTick',-1,...
                         'Expire',-1,'WExpire',-1,...
                         'Ala',1.0,'it','ap'));
buffs=struct('BF',struct('LastUsed',-1,'Available',0,'Dur',15,'CD',120),...
             'AD',struct('LastUsed',-1,'Available',0,'Dur',15),...
             'BARelic',struct('LastUsed',-1,'Available',0,'Dur',30));
procs=struct('FR',struct('LastProc',-1,'Dur',6,'CD',20),...
             'SA',struct('LastProc',-1,'Dur',6,'CD',20),...
             'PC2',struct('LastProc',-1,'Dur',15,'CD',30,'Available',0),...
             'AC',struct('LastProc',-1,'Dur',30,'CD',60),...
             'IA',struct('LastProc',-1,'Dur',10,'CD',6,'Ala',0.0),...
             'EL',struct('LastProc',-1,'Dur',-1,'CD',-1,'Charges',0));
                           
z=struct('abilities',abilities,'dots',dots,'buffs',buffs,'procs',procs);
json.savejson('',z,'json/Tactics.json');

abilities.ts.name='Magnetic Blast';
abilities.ss.name='Rocket Punch';
abilities.gut.name='Retractable Blade';
abilities.gutd.name='RBlade DOT';
abilities.hib.name='Rail Shot';
abilities.cb.name='Energy Burst';
abilities.hs.name='Rapid Shots';
abilities.hs.ticks=5;
abilities.ap.name='Thermal Detonator';

                          
z=struct('abilities',abilities,'dots',dots,'buffs',buffs,'procs',procs);
json.savejson('',z,'json/AP.json');